---
name: pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        run: ./gradlew

      - name: Build
        run: ./gradlew build

  release:
    needs: build
    permissions:
      contents: write  # needed for the release script

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Build
        run: ./gradlew build

      - name: Create tag name
        id: tag-name
        run: echo "RELEASE_TAG_NAME=`date +%s`" >> "$GITHUB_OUTPUT"

      - name: Create new tag
        run: git tag ${{steps.tag-name.outputs.RELEASE_TAG_NAME}}

      - name: Push new tag
        run: git push origin ${{steps.tag-name.outputs.RELEASE_TAG_NAME}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tag-name.outputs.RELEASE_TAG_NAME}}
          files: ./build/distributions/kang-latest.zip
